# Generated by Django 3.1.1 on 2020-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_depretiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ite_depretiation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
