# Generated by Django 3.1.1 on 2020-09-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200916_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='account_type',
        ),
        migrations.AddField(
            model_name='cvbase',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accountsub'),
        ),
    ]
