# Generated by Django 3.1.1 on 2020-09-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200916_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvbase',
            name='account_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='core.accountsub'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_type',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='core.accountsub'),
        ),
    ]
