# Generated by Django 3.1.1 on 2020-09-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200916_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accountsub'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sender_model',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accountsub'),
        ),
    ]
