# Generated by Django 3.1.1 on 2020-09-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('depreciation_choices', models.PositiveIntegerField(choices=[(1, 'Depreciation'), (2, 'Prepaid'), (3, 'Supplies')])),
                ('year_of_purchase', models.IntegerField()),
                ('lifespan', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Depretiation',
        ),
    ]
