# Generated by Django 3.1.1 on 2020-09-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200928_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='amount',
        ),
    ]
