# Generated by Django 3.1.1 on 2020-09-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
    ]
