# Generated by Django 3.1.2 on 2020-10-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20201003_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice'),
        ),
    ]
