# Generated by Django 3.1.2 on 2020-10-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20201004_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(default='unpaid', max_length=30),
        ),
    ]
