# Generated by Django 3.1.2 on 2020-10-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20201005_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttemplate',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
