# Generated by Django 3.1.2 on 2020-10-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_sale_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='core.invoice'),
        ),
    ]
