# Generated by Django 3.1.2 on 2020-10-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_sale_invoice'),
        ('core', '0045_accounttemplate_balance'),
    ]

    operations = [
    ]
