# Generated by Django 3.1.2 on 2020-10-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20201006_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('payment_term', models.CharField(choices=[('cash', 'CASH'), ('Credit Card', 'CREDIT CARD'), ('Cheque', 'CHEQUE')], default='cash', max_length=60)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('invoked', 'INVOKED'), ('paid', 'PAID')], default='pending', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.vendor')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='VendorInvoice',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.purchaseinvoice'),
        ),
    ]
