# Generated by Django 3.1.2 on 2020-10-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20201006_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total',
        ),
    ]
