# Generated by Django 3.1.1 on 2020-09-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dr', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cr', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('share', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_account', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMain',
            fields=[
                ('accounttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.accounttemplate')),
                ('account_section', models.CharField(choices=[('Assets', 'ASSETS'), ('Liabilities', 'LIABILITIES'), ('Equity', 'EQUITY'), ('Revenue', 'REVENUE'), ('Expense', 'EXPENSE')], max_length=30)),
            ],
            bases=('core.accounttemplate',),
        ),
        migrations.CreateModel(
            name='AccountSub',
            fields=[
                ('accounttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.accounttemplate')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accountmain')),
            ],
            bases=('core.accounttemplate',),
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('accounttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.accounttemplate')),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('account_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accountsub')),
            ],
            bases=('core.accounttemplate',),
        ),
        migrations.AddField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(to='core.Owner'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('transactiontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transactiontype')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            bases=('core.transactiontype',),
        ),
        migrations.AddField(
            model_name='accountmain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
