# Generated by Django 3.1.1 on 2020-09-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_type',
            field=models.CharField(choices=[('accrual', 'ACCRUAL'), ('cash', 'CASH')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='accrual', max_length=200),
            preserve_default=False,
        ),
    ]
