# Generated by Django 3.1.1 on 2020-09-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='paren_company',
            new_name='parent_company',
        ),
        migrations.AlterField(
            model_name='company',
            name='account_type',
            field=models.CharField(choices=[('accrual', 'ACCRUAL'), ('cash', 'CASH')], default='accrual', max_length=20),
        ),
    ]
