# Generated by Django 3.1.1 on 2020-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
