# Generated by Django 3.1.1 on 2020-09-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_ite_depretiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.accountsub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='model',
            field=models.CharField(choices=[('Purchase', 'PURCHASE'), ('Sale', 'SALE'), ('Payment', 'PAYMENT'), ('Receive', 'RECEIVE')], default='Purchase', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='model_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
