# Generated by Django 3.1.1 on 2020-09-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='cr',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='dr',
        ),
        migrations.AddField(
            model_name='journal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='journal',
            name='cr_account',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='core.accountsub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='dr_account',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='debit_account', to='core.accountsub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='model_id',
            field=models.PositiveIntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='sender_model',
            field=models.CharField(choices=[('Purchase', 'PURCHASE'), ('Sale', 'SALE'), ('Payment', 'PAYMENT'), ('Receive', 'RECEIVE')], default=14, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accountsub'),
        ),
    ]
