# Generated by Django 3.1.1 on 2020-09-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200919_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsp',
            name='year_of_purchase',
        ),
    ]
