# Generated by Django 3.1.1 on 2020-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_cvbase_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
