# Generated by Django 3.1.2 on 2020-10-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20201001_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('invoked', 'INVOKED'), ('paid', 'PAID')], default='pending', max_length=30),
        ),
    ]
