# Generated by Django 3.1.2 on 2020-10-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20201006_1557'),
        ('core', '0047_merge_20201005_2134'),
    ]

    operations = [
    ]
