# Generated by Django 5.2.5 on 2025-08-17 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0053_alter_journal_model_id_alter_journal_sender_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='journal',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
