# Generated by Django 5.2 on 2025-09-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_alter_menu_options_rename_name_menu_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='tree_id',
        ),
    ]
