# Generated by Django 5.2 on 2025-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_remove_menu_level_remove_menu_lft_remove_menu_rght_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
