# Generated by Django 3.1.1 on 2020-09-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200916_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvbase',
            name='account_type',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='core.accountsub'),
        ),
    ]
