# Generated by Django 3.1.1 on 2020-09-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200919_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ite_depretiation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='item_depretiation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dsp'),
            preserve_default=False,
        ),
    ]
