# Generated by Django 3.1.1 on 2020-09-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_dsp_year_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sale_items',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
