# Generated by Django 3.1.1 on 2020-09-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_invoice_payment_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvbase',
            name='address',
        ),
    ]
