# Generated by Django 3.1.1 on 2020-09-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_cvbase_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvbase',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
    ]
