# Generated by Django 5.2.5 on 2025-08-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20201006_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='model_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sender_model',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice'),
        ),
    ]
