# Generated by Django 5.2 on 2025-08-20 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dr', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_section', models.CharField(choices=[('Assets', 'ASSETS'), ('Liabilities', 'LIABILITIES'), ('Equity', 'EQUITY'), ('Revenue', 'REVENUE'), ('Expense', 'EXPENSE')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dr', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.accountmain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
