# Generated by Django 5.2 on 2025-08-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMain',
            fields=[
                ('accounttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.accounttemplate')),
                ('account_section', models.CharField(choices=[('Assets', 'ASSETS'), ('Liabilities', 'LIABILITIES'), ('Equity', 'EQUITY'), ('Revenue', 'REVENUE'), ('Expense', 'EXPENSE')], max_length=30)),
            ],
            bases=('core.accounttemplate',),
        ),
        migrations.CreateModel(
            name='AccountSub',
            fields=[
                ('accounttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.accounttemplate')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.accountmain')),
            ],
            bases=('core.accounttemplate',),
        ),
    ]
